name: Actions Workflow

on:
 push:
   branches:
     - master
     - "feature/*"
     - "feature/**"
     - "!feature/featc"
   tags: 
  schedule:
          # - cron: "0/2 * * * *"
          # - cron: "0/3 * * * *"
  # push
  pull_request:
    types: [closed, assigned, opened, reopened]


jobs:
  run-github-actions:
    runs-on: ubuntu latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
